info:
  app:
    description: This is a SpringBoot Demo app
    name: Beginning Spring Boot 2 by Arun k
    version: 1.0.0
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: true
  server:
    servlet:
      context-path: /management
spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: secret
      roles: USER,ADMIN,ACTUATOR
  config:
    activate:
      on-profile: docker
enabled: true
