info:
  app:
    description: This is a SpringBoot Demo app
    name: Beginning Spring Boot 2 by Arun k
    version: 1.0.0
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: true
  server:
    servlet:
      context-path: /management
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_ENV_POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR}:${POSTGRES_PORT_5432_TCP_PORT}/demodb
    username: ${POSTGRES_ENV_POSTGRES_USER}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: secret
      roles: USER,ADMIN,ACTUATOR
